name: Build & Deploy Spring App
on:
  push:
    branches:
      - main
    paths:
      - ride_fast_backend/**
      - .github/**
jobs:
  build-deploy:
    name: Build and Deploy Spring Boot application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: 17

      # - name: Unit Tests
      #   run: mvn -B test --file ride_fast_backend/pom.xml

      - name: Package and Build the application
        run: |
          cd ride_fast_backend
          mvn clean
          mvn -B package -DskipTests --file pom.xml

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./ride_fast_backend
          push: false
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/ride-fast-app-backend:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

      - name: Push Image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: ./ride_fast_backend
          push: true
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/ride-fast-app-backend:latest
